# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name=b'URL')),
                ('response_code', models.IntegerField()),
                ('visited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name=b'URL')),
                ('response_code', models.IntegerField(null=True)),
                ('visited_date', models.DateTimeField(auto_now=True)),
                ('visited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RequestException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('status_code', models.IntegerField(null=True)),
                ('response_content', models.TextField(null=True)),
                ('response_header', models.TextField(null=True)),
                ('visited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='profilepage',
            name='exception',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper_app.RequestException'),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper_app.ListPage'),
        ),
        migrations.AddField(
            model_name='listpage',
            name='exception',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper_app.RequestException'),
        ),
    ]
